// Generated by dia2code
#ifndef CLIENT__CLIENT__H
#define CLIENT__CLIENT__H


namespace client {

  /// class client - 
  class client {
    // Operations
  public:
    void helloWorld ();
    // Setters and Getters
  };

};

#endif
