// Generated by dia2code
#ifndef CLIENT__HELLO__H
#define CLIENT__HELLO__H


namespace client {

  /// class hello - 
  class hello {
    // Operations
  public:
    void helloWorld ();
    // Setters and Getters
  };

};

#endif
